# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
        migrations.AddField(
            model_name='medium',
            name='filter',
            field=models.SlugField(default=django.utils.timezone.now, max_length=150, verbose_name='Data Filter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=150, verbose_name='Client Company Name'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
