# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Company Name')),
                ('history', models.CharField(max_length=250, verbose_name='History')),
                ('whatwedo', models.CharField(max_length=250, verbose_name='What We Do')),
                ('whoweare', models.TextField(verbose_name='Who We Are')),
                ('mission', models.CharField(max_length=250, verbose_name='Our Mission')),
                ('vision', models.CharField(max_length=250, verbose_name='our Vision')),
                ('corevalues', models.CharField(max_length=250, verbose_name='our Core Values')),
            ],
        ),
        migrations.CreateModel(
            name='AboutFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('client_feed', models.TextField(verbose_name='Client Feedback')),
                ('client_position', models.CharField(max_length=100, verbose_name='Client Position/Rank')),
                ('client_company', models.CharField(max_length=250, verbose_name='Client Company')),
                ('client_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('client_logo', models.ImageField(upload_to='clients', verbose_name='Client Company Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancyservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cservice_name', models.CharField(max_length=100, verbose_name='Consultancy Service Name')),
                ('cservice_desc', models.CharField(max_length=500, verbose_name='Consultancy Service Brief Description')),
                ('cservice_detail', models.TextField(verbose_name='Consultancy Service Details')),
                ('cservice_icon', models.CharField(default='user', max_length=50, verbose_name='Consultancy Service Icon')),
            ],
            options={
                'verbose_name_plural': 'Consultancyservices',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_desc', models.CharField(max_length=500, verbose_name='Service Brief Description')),
                ('service_detail', models.TextField(verbose_name='Service Details')),
                ('service_icon', models.CharField(default='desktop', max_length=50, verbose_name='Service Icon')),
                ('service_percent', models.IntegerField(blank=True, verbose_name='Service Proficiency Percent')),
                ('service_image', models.ImageField(upload_to='services', verbose_name='Service Image')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254, verbose_name='Staff Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('fb_username', models.CharField(max_length=100, verbose_name='Facebook Username')),
                ('twitter_handle', models.CharField(blank=True, max_length=100, verbose_name='Twitter Handle')),
                ('linkedin_username', models.CharField(blank=True, max_length=100, verbose_name='Linkedin Username')),
                ('dribble_username', models.CharField(blank=True, max_length=100, verbose_name='Dribble Username')),
                ('image_url', models.ImageField(upload_to='projects', verbose_name='Staff Image')),
            ],
        ),
    ]
