# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfeed',
            name='client_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='clients/pics', verbose_name="Client's Profile Picture"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutfeed',
            name='job_desc',
            field=models.TextField(blank=True, verbose_name="Client's Job Description"),
        ),
        migrations.AddField(
            model_name='staff',
            name='office_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='Work/Office Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='corevalues',
            field=models.CharField(max_length=500, verbose_name='our Core Values'),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=models.CharField(max_length=500, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.CharField(max_length=500, verbose_name='Our Mission'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.CharField(max_length=500, verbose_name='our Vision'),
        ),
        migrations.AlterField(
            model_name='about',
            name='whatwedo',
            field=models.CharField(max_length=500, verbose_name='What We Do'),
        ),
        migrations.AlterField(
            model_name='aboutfeed',
            name='client_feed',
            field=models.TextField(blank=True, verbose_name='Client Feedback'),
        ),
        migrations.AlterField(
            model_name='aboutfeed',
            name='client_logo',
            field=models.ImageField(upload_to='clients/logo', verbose_name='Client Company Logo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='fb_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook Username'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image_url',
            field=models.ImageField(upload_to='staff', verbose_name='Staff Profile Image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Mobile Phone Number'),
        ),
    ]
